config/routes.rb
Rails.application.routes.draw do

    root  'home_page#index'
    match '/miss',  to: 'home_page#gallery',  via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_page_controller.rb
class HomePageController < ApplicationController

	def index

	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_page_helper.rb
module HomePageHelper
end

app/views/home_page/gallery.html.erb
<script type = "text/javascript">
		//<![CDATA[

			// Automates the diagonalFade effect
			function slideshow(selector, _f) {

				var x = parseInt(Math.random() * 2); // left-right
				var y = parseInt(Math.random() * 2); // top-bototm
				var f = _f; // fade out || fade in

				if(x > 0) x = 'left-right';
				else      x = 'right-left';

				if(y > 0) y = 'top-bottom';
				else      y = 'bottom-top';

				var s = 'out';

				if(f) {
					s = 'in';
					f = false;
				} else {
					s = 'out';
					f = true;
				}

				$(selector).diagonalFade({
					time: 150,
					fadeDirection_x: x,
					fadeDirection_y: y,
					fade: s,
					complete: function() {
						slideshow(selector, f);
					}
				});
			}

			$(function() {

				// select our containers and execute the slideshow
				slideshow("#image_cascade", false);
				slideshow("#text_cascade", false);
			});


		//]]>
	</script>




	<div class = "container_9 section">


	</div>


	<div id = "image_cascade" class = "container_9">

		<%= image_tag "image_part_001.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_002.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_003.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_004.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_005.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_006.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_007.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_008.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_009.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_010.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_011.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_012.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_013.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_014.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_015.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_016.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_017.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_018.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_019.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_020.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_021.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_022.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_023.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_024.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_025.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_026.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_027.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_028.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_029.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_030.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_031.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_032.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_033.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_034.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_035.jpg", :height => 125, :class => "grid_1"  %>
		<%= image_tag "image_part_036.jpg", :height => 125, :class => "grid_1"  %>


		<div class = "clear"></div>

	</div>

app/views/home_page/index.html.erb
<div clalss="container-fluid ">
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
	<div class="row">
		<div class="col-md-4">
		</div>
		<div class="col-md-4">
			<%= link_to "Нажать тут!",  miss_path,  class: "btn btn-primary btn-lg center-block" %>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Miss</title>

	<link href = "gs.css"    media = "screen" rel = "stylesheets" type = "text/css" />
	<link href = "style.css" media = "screen" rel = "stylesheets" type = "text/css" />
  <script type = "text/javascript" src = "http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
  <script type = "text/javascript" src = "jquery.diagonalFade.js"></script>



  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>


</body>
</html>